name: Daily News Image Generator

on:
  schedule:
    - cron: '0 8 * * *'  # Runs at 8:00 AM UTC daily
  workflow_dispatch:      # Allows manual trigger

jobs:
  generate-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Needed for pushing to the repository

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod download

    - name: Generate Image
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        go run main.go
        
    - name: Setup git config
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"

    - name: Commit and push if there are changes
      run: |
        # Move generated image to images directory with date-based name
        mkdir -p images
        DATE=$(date +%Y-%m-%d)
        mv generated_images/combined_news.png "images/news-${DATE}.png"
        
        # Stage and commit changes
        git add images/
        git commit -m "Add news image for ${DATE}" || exit 0
        git push 